version: 2
jobs:
  build_base_ros:
    machine: true
    working_directory: ~/project/images/base_ros
    steps:
      - checkout

      - run: run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - run: docker build -t $DOCKER_USERNAME/base_ros:alpha .

      - run: docker push $DOCKER_USERNAME/base_ros:alpha && sleep 10

      - store_artifacts:
        path: /results
