version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: login dockerhub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - run:
          name: build base_ros docker image
          command: |
            cd images/base_ros
            docker build -t $DOCKER_USERNAME/base_ros:alpha .

      - run:
          name: upload base_ros image to dockerhub
          command: |
            docker push $DOCKER_USERNAME/base_ros:alpha && sleep 10

      - run:
          name: build ros_gazebo docker image
          command: |
            cd images/ros_gazebo
            docker build -t $DOCKER_USERNAME/ros_gazebo:alpha .

      - run:
          name: upload ros_gazebo image to dockerhub
          command: |
            docker push $DOCKER_USERNAME/ros_gazebo:alpha && sleep 10

      - run:
          name: build ros_gazebo_node docker image
          command: |
            cd images/ros_gazebo_node
            docker build -t $DOCKER_USERNAME/ros_gazebo_node:alpha .

      - run:
          name: upload ros_gazebo_node image to dockerhub
          command: |
            docker push $DOCKER_USERNAME/ros_gazebo_node:alpha && sleep 10

      - run:
          name: build ros_websim docker image
          command: |
            cd images/ros_websim
            docker build -t $DOCKER_USERNAME/ros_websim:alpha .

      - run:
          name: upload ros_websim image to dockerhub
          command: |
            docker push $DOCKER_USERNAME/ros_websim:alpha && sleep 10

      - store_artifacts:
          path: /results
