version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout

      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - run:
          name: build base_ros docker image
          command: |
            cd images/base_ros
            docker build -t $DOCKER_USERNAME/base_ros:alpha .

      - run: docker push $DOCKER_USERNAME/base_ros:alpha && sleep 10

      - store_artifacts:
          path: /results
