version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo/images/base_ros
    steps:
      - checkout

      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - run: docker build -t $DOCKER_USERNAME/base_ros:alpha .

      - run: docker push $DOCKER_USERNAME/base_ros:alpha && sleep 10

      - store_artifacts:
          path: /results
